export { default as AboutMe } from "./AboutMe/AboutMe.tsx"
export { default as Contacts } from "./Contacts/Contacts.tsx"
export { default as Header } from "./Header/Header.tsx"
export { default as Intro } from "./Intro/Intro.tsx"
export { default as Services } from "./Services/Services.tsx"
export { default as Skills } from "./Skills/Skills.tsx"
